### ISSUE TITLE
Data pipeline broken

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#187]
Data pipeline fails with following error

```sh
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/papermill/execute.py", line 128, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/runner/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 data = pd.read_csv(EVENTS_RAW_DATA)[columns.keys()].rename(columns=columns)
      2 data.time = pd.to_datetime(data.time, errors='coerce')

File ~/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/pandas/core/frame.py:3767, in DataFrame.__getitem__(self, key)
   3765     if is_iterator(key):
   3766         key = list(key)
-> 3767     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3769 # take() does not accept boolean indexers
   3770 if getattr(indexer, "dtype", None) == bool:

File ~/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/pandas/core/indexes/base.py:5877, in Index._get_indexer_strict(self, key, axis_name)
   5874 else:
   5875     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 5877 self._raise_if_missing(keyarr, indexer, axis_name)
   5879 keyarr = self.take(indexer)
   5880 if isinstance(key, Index):
   5881     # GH 42790 - Preserve name from an Index

File ~/.local/share/virtualenvs/leeds-2023-a_g5KJIi/lib/python3.10/site-packages/pandas/core/indexes/base.py:5941, in Index._raise_if_missing(self, key, indexer, axis_name)
   5938     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   5940 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 5941 raise KeyError(f"{not_found} not in index")

KeyError: "['displayOnWebsite'] not in index"

ERROR: failed to reproduce 'scripts/metrics/promote-events/dvc.yaml:transform': failed to run: papermill transform.ipynb ../../../working/output/promote-events-transform.ipynb, exited with 1
Error: Process completed with exit code 255.
```

**Comment by gilesdring** [comment]
Looks like one of the fields (`displayOnWebsite`) is no longer being downloaded for some reason.

```py
columns = {
    'id': 'id',
    'name': 'name',
    'locationName': 'location',
    'cardPrice': 'card_price',
    'timeslots': 'time',
    # 'displayOnWebsite': 'display',
    'Stage': 'stage',
}
```


Having worked around that, came up with the following subsequent issue in Cision processing:

```
Running stage 'scripts/metrics/media/dvc.yaml:transform':                                                                                                                                                                                                      
> PYTHONPATH=scripts python3 scripts/metrics/media/transform_cision.py
Traceback (most recent call last):
  File "/home/giles/.local/share/virtualenvs/leeds-2023-YZF5GfJv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'news_headline'
```

**Comment by gilesdring** [comment]
This is because the media file `working/manual/media/Leeds 2023 weekly media coverage 29.07-18.08.23.csv` has no headers
